#!/bin/sh
#Add Tiny Tiny to default folder
echo "\n\nListen 8010 \n\n<VirtualHost *:8010>\n\n\tServerName dev.thelatest.com:8010\n\tServerAdmin arivera@kodetec.com\n\tDocumentRoot /var/www/tt-rss\n\n\t<Directory /var/www/tt-rss>\n\t\tOptions Indexes FollowSymLinks Includes ExecCGI\n\t\tAllowOverride All\n\t\tOrder allow,deny\n\t\tAllow from all\n\t</Directory>\n\n\tErrorLog \${APACHE_LOG_DIR}/error.log\n\tCustomLog \${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>" | sudo tee -a /etc/apache2/sites-available/000-default.conf && \
#update permision to different folders, according to tiny-tiny instrucctions
sudo chmod -R 777 /var/www/tt-rss/cache/images /var/www/tt-rss/cache/upload /var/www/tt-rss/cache/export /var/www/tt-rss/cache/js /var/www/tt-rss/feed-icons /var/www/tt-rss/lock && \
#create database
sudo -u postgres psql -U postgres -d postgres -c "CREATE DATABASE tt_rss ENCODING 'UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE template0;" && \
sudo -u postgres psql -U postgres -d tt_rss -a -f tt_rss_initial_config.sql && \
#create configuration file for Tiny-Tiny and set configurations
sudo touch /var/www/tt-rss/config.php && \
echo "<?php \n\n\tdefine('DB_TYPE', 'pgsql');\n\tdefine('DB_HOST', 'localhost');\n\tdefine('DB_USER', 'postgres');\n\tdefine('DB_NAME', 'tt_rss');\n\tdefine('DB_PASS', 'postgres');\n\tdefine('DB_PORT', '5432');\n\n\tdefine('MYSQL_CHARSET', 'UTF8');\n\tdefine('SELF_URL_PATH', 'http://192.168.68.92:8010/');\n\n\tdefine('FEED_CRYPT_KEY', '');\n\n\tdefine('SINGLE_USER_MODE', false);\n\n\tdefine('SIMPLE_UPDATE_MODE', false);\n\n\tdefine('PHP_EXECUTABLE', '/usr/bin/php');\n\n\tdefine('LOCK_DIRECTORY', 'lock');\n\n\tdefine('CACHE_DIR', 'cache');\n\n\tdefine('ICONS_DIR', 'feed-icons');\n\n\tdefine('ICONS_URL', 'feed-icons');\n\n\tdefine('AUTH_AUTO_CREATE', true);\n\n\tdefine('AUTH_AUTO_LOGIN', true);\n\n\tdefine('FORCE_ARTICLE_PURGE', 0);\n\n\tdefine('PUBSUBHUBBUB_HUB', '');\n\n\tdefine('PUBSUBHUBBUB_ENABLED', false);\n\n\tdefine('SPHINX_SERVER', 'localhost:9312');\n\n\tdefine('SPHINX_INDEX', 'ttrss, delta');\n\n\tdefine('ENABLE_REGISTRATION', false);\n\n\tdefine('REG_NOTIFY_ADDRESS', 'user@your.domain.dom');\n\n\tdefine('REG_MAX_USERS', 10);\n\n\tdefine('SESSION_COOKIE_LIFETIME', 86400);\n\n\tdefine('SESSION_CHECK_ADDRESS', 1);\n\n\tdefine('SMTP_FROM_NAME', 'Tiny Tiny RSS');\n\n\tdefine('SMTP_FROM_ADDRESS', 'noreply@your.domain.dom');\n\n\tdefine('DIGEST_SUBJECT', '[tt-rss] New headlines for last 24 hours');\n\n\tdefine('SMTP_SERVER', '');\n\n\tdefine('SMTP_LOGIN', '');\n\tdefine('SMTP_PASSWORD', '');\n\n\tdefine('SMTP_SECURE', '');\n\n\tdefine('CHECK_FOR_UPDATES', true);\n\n\tdefine('DETECT_ARTICLE_LANGUAGE', false);\n\n\tdefine('ENABLE_GZIP_OUTPUT', false);\n\n\tdefine('PLUGINS', 'auth_internal, note');\n\n\tdefine('LOG_DESTINATION', 'sql');\n\n\tdefine('CONFIG_VERSION', 26);" | sudo tee -a /var/www/tt-rss/config.php

